### PR TITLE
Fixed:timer_settime failes on 32bit linux

### PR DESCRIPTION
**Pull request by yTakatsukasa**
Hi Edgar,
I hit an error on 32bit linux.
Calling timer_settime() in tlmu_hosttimer_start(int64_t) sometimes emits an error.
It is because timeout.it_interval.tv_sec is negative value.
time_t is 32bit signed integer on 32bit platform.

When no timers are found in tlmu_timers_run(),  it returns INT64_MAX.
And it cause overflow in timer_settime() and tv_sec is then negative.
I changed tlmu_timers_run() to set "next_deadline" 1sec future if notimers are found.
I am not sure 1sec(default_next_timer_check_ns) is optimal or not.
Please fix the value if you find better value.

BTW the previous pull request looks still open on github.com.

Regards, Yutestu.

### CODE REVIEW

**Comment by edgarigl** [comment]
On Sun, Sep 30, 2012 at 09:21:12PM -0700, Yutetsu TAKATSUKASA wrote:

>    Hi Edgar,
>    I hit an error on 32bit linux.
>    Calling timer_settime() in tlmu_hosttimer_start(int64_t) sometimes
>    emits an error.
>    It is because timeout.it_interval.tv_sec is negative value.
>    time_t is 32bit signed integer on 32bit platform.
> 
>    When no timers are found in tlmu_timers_run(), it returns INT64_MAX.
>    And it cause overflow in timer_settime() and tv_sec is then negative.
>    I changed tlmu_timers_run() to set "next_deadline" 1sec future if
>    notimers are found.
>    I am not sure 1sec(default_next_timer_check_ns) is optimal or not.
>    Please fix the value if you find better value.

Thanks for investigating this, I've merged your patch.

I'm not sure either. A larger value might be better but it should only
be an optimization issue IIUC.

>    BTW the previous pull request looks still open on github.com.

Hmm yes, I've merged but maybe github gets confused because we
iterated and I didn't end up merge:ing the exact sha that was
posted.

Best regards,
Edgar

**Comment by yTakatsukasa** [comment]
Thanks for the quick merging.

> I'm not sure either. A larger value might be better but it should only be an optimization issue IIUC.

I agree with you.
But now I come to think skip calling timer_settimer() is better way when no timers are found.
Timer will expire 300 billion year future if no timers are found in conventional implementation.
It means timers will never expire.

Anyway I am not sure how tlmu_timer works and its purpose. 
I will try in my free time. :)

Regards,
Yutetsu.

**Comment by yTakatsukasa** [comment]
> > BTW the previous pull request looks still open on github.com.
> 
> Hmm yes, I've merged but maybe github gets confused because we iterated and I didn't end up merge:ing the exact sha that was posted.

FYI
I could close the pull request from web interface of github.com
After I clicked the Close button in the page below, pull request is closed.
https://github.com/edgarigl/tlmu/pull/3

Regards,
Yutetsu.

**Comment by edgarigl** [comment]
On Tue, Oct 02, 2012 at 06:25:15AM -0700, Yutetsu TAKATSUKASA wrote:

>    Thanks for the quick merging.
> 
> ```
>  I'm not sure either. A larger value might be better but it should
>  only be an optimization issue IIUC.
> ```
> 
>    I agree with you.
>    But now I come to think skip calling timer_settimer() is better way
>    when no timers are found.
>    Timer will expire 300 billion year future if no timers are found in
>    conventional implementation.
>    It means timers will never expire.

That sounds like a good idea!

Best regards,
Edgar

**Pull request closed without merging**
